### ISSUE TITLE
marginpolish core dumps on test file

### ISSUE THREAD

**Issue by rcurrie** [ucsc-upd/pipelines#1]
Marginpolish appears to mostly run fine after all prior steps in secondary run but at the end it core dumps and fails to generate the marginPolish directory:
```
...
left-trim: 98, right-trim: 3:
  Removed overlap between neighbouring chunks. Approx overlap size: 100, overlap-match weight: 1.000000,
left-trim: 98, right-trim: 3:
Command terminated by signal 11
```

**Comment by rcurrie** [comment]
I think it may be the smaller test sample, running with the larger one and will report back.

**Comment by rcurrie** [comment]
Looks like it was something to do with the ecoli sample, generated output with GM24385.chr20 so closing.

**Comment by kishwarshafin** [comment]
wait, were you able to run HELEN too?
