### ISSUE TITLE
Need 'good' tertiary added to Makefile

### ISSUE THREAD

**Issue by rcurrie** [ucsc-upd/pipelines#3]
@adamnovak @cmarkello Assuming a bam exists from the secondary steps in the Makefile can you cook up a 'good' (could be GATK...) to generate a vcf? The test file is ecoli just to run fast but will switch over to the chr20 that trevor pointed to so if you want to start with that bam on your way to a vcf that works. I can add in the details on reference download if we need it patterned after the [treehouse makefile](https://github.com/UCSC-Treehouse/pipelines/blob/master/Makefile).

**Comment by rcurrie** [comment]
I'm going to try and paste in a cheap and cheerful freebayes snippet to call variants as a 'sub-good' start.

**Comment by rcurrie** [comment]
I have mapping to hg38 and variant calling ceremony hooked up and running, but, after 20 hours freebayes is still running on the test sample. @adamnovak @cmarkello @rlorigro or anyone else have any knowledge of using freebayes on long reads like this? Or suggestions on an alternative variant caller? Freebayes is single threaded but should be faster then this - at least that is my albeit very limited experience using it on short reads (DNA and RNA).

**Comment by adamnovak** [comment]
Maybe we want to bring in @ekg for this question, seeing as he wrote it. Erik, do you have any idea if Freebayes is expected to take over 20 hours on nanopore reads, or if not how to tell what might have gone wrong with it?

**Comment by rcurrie** [comment]
@ekg specifically we're using [GM24385.chr20](https://lc2019.s3-us-west-2.amazonaws.com/sample_data/GM24385/GM24385.chr20.fq) against HG38 as a test.

**Comment by rcurrie** [comment]
With the latest tooling I've been running freebayes for ~20+ hours o this chr20 sample. Tailing the VCF being generated its up to 266124 (assuming its going sequentially as the bam is sorted).  That's very very roughly 266124/64444167 or .4% of the way through so something must be seriously wrong. The single core is at 100% and using 1.9G memory and the VCF is up to 28M at this point so I strongly suspect user error. Anyone else have experience with freebayes on long reads mapped with minimap against HG38?

**Comment by rcurrie** [comment]
For convenience here is the invocation:
```
Calling variants against hg38...
docker run -it --rm --cpus="64" -v `realpath data/test`:/data \
        -v `realpath data/references`:/references \
        --user=`id -u`:`id -g` \
        quay.io/ucsc_cgl/freebayes@sha256:b467edda4f92f22f0dc21e54e69e18bfd6dcc5cbe3292e108429e2d86034e6e5 \
        --fasta-reference /references/hg38.fa \
        --vcf /data/test.hg38.vcf \
        /data/test.minimap2_hg38_sorted.bam
```

**Comment by rcurrie** [comment]
Clairvoyante seems to be running well and fast. Closing until we all talk in person about what other options that might involve VG, or options around benchmarking Clairvoyante and focusing on finding things that the short read exome sequencing @ UCLA might have missed that nanopore/longer reads might elucidate.
